"""Repository interfaces (contract). SQLite-реализация — sqlite_repo.py.

Задел под MongoDB: бизнес-логика (services) зависит только от этих методов;
смена хранилища = новая реализация без правки сервисов/роутов.
"""
from __future__ import annotations

from typing import Any, Protocol


class Repo(Protocol):
    # ---- users ----
    def create_user(self, email: str, password_hash: str, name: str, role: str, is_active: int = 1) -> dict: ...
    def get_user_by_email(self, email: str) -> dict | None: ...
    def get_user(self, user_id: int) -> dict | None: ...
    def list_users(self) -> list[dict]: ...
    def update_user(self, user_id: int, **fields: Any) -> None: ...
    def count_users(self) -> int: ...

    # ---- books ----
    def create_book(self, owner_id: int, **fields: Any) -> int: ...
    def get_book(self, book_id: int) -> dict | None: ...
    def list_books(self, owner_id: int) -> list[dict]: ...
    def update_book(self, book_id: int, **fields: Any) -> None: ...
    def delete_book(self, book_id: int) -> None: ...
    def touch_book(self, book_id: int) -> None: ...

    # ---- chapters ----
    def replace_chapters(self, book_id: int, chapters: list[dict]) -> None: ...
    def list_chapters(self, book_id: int) -> list[dict]: ...
    def get_chapter(self, chapter_id: int) -> dict | None: ...
    def get_chapter_by_num(self, book_id: int, num: int) -> dict | None: ...
    def update_chapter(self, chapter_id: int, **fields: Any) -> None: ...
    def count_chapters(self, book_id: int, status: str | None = None) -> int: ...

    # ---- jobs ----
    def create_job(self, **fields: Any) -> int: ...
    def get_job(self, job_id: int) -> dict | None: ...
    def list_jobs(self, book_id: int | None = None, owner_id: int | None = None) -> list[dict]: ...
    def update_job(self, job_id: int, **fields: Any) -> None: ...
    def claim_job(self, job_id: int) -> bool: ...
    def next_queued_jobs(self, limit: int, exclude_ids: tuple[int, ...]) -> list[dict]: ...

    # ---- settings / progress ----
    def get_setting(self, key: str, default: str = "") -> str: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def all_settings(self) -> dict: ...
    def get_progress(self, user_id: int, book_id: int) -> dict | None: ...
    def set_progress(self, user_id: int, book_id: int, chapter_num: int, position_sec: float) -> None: ...
